import test from 'node:test';import assert from 'node:assert/strict';import {spawn} from 'node:child_process';import fs from 'node:fs/promises';import os from 'node:os';import path from 'node:path';
import {sabrIV,fitSABR,deltaSkew,gammaExposure,quoteUsable} from '../core/option-surface.js';
import {OptionHistory,OptionRecorder,validateOptionSnapshot} from '../core/option-history.js';
import {portfolioRisk,strategyCandidates,backtestOptions} from '../core/option-portfolio.js';
import {PublicOptionsExchange,bybitRows,okxRows,exchangeRequest} from '../core/crypto-exchanges.js';
import {optionFixture} from './fixtures/option-chain.js';
const near=(a,b,t=1e-7)=>assert.ok(Math.abs(a-b)<t,`${a} != ${b}`),memory=()=>{const m=new Map();return {read:async(k,id='current')=>structuredClone(m.get(k+id)??null),write:async(k,v,id='current')=>{m.set(k+id,structuredClone(v));return v;},remove:async(k,id)=>m.delete(k+id)};};
test('Hagan SABR matches independent QuantLib 1.43 references including ATM continuity',()=>{
 const refs=[[50,.3073338359562752],[90,.21467028255329446],[100,.20179000000000002],[100.000001,.2017899988912383],[110,.1924172873529628],[150,.18139442633564695]];
 for(const [K,expected] of refs)near(sabrIV(100,K,1,{alpha:2,beta:.5,rho:-.3,nu:.4}),expected,1e-13);assert.throws(()=>sabrIV(100,100,1,{alpha:2,beta:.5,rho:1,nu:.4}));
});
test('SABR recovers known parameters, withholds diagnostic points, gates stale/missing/wide quotes and checks bounds',()=>{
 const s=optionFixture(),fit=fitSABR(s,{expiry:s.rows[0].expiry});assert.equal(fit.converged,true);near(fit.params.alpha,2,1e-5);near(fit.params.rho,-.3,1e-5);near(fit.params.nu,.4,1e-5);assert.ok(fit.trainRMSE<.0001&&fit.holdoutRMSE<.0001);assert.ok(fit.residuals.some(r=>r.usedFor==='held out'));assert.ok(fit.curve.every(r=>Number.isFinite(r.iv)));
 assert.equal(quoteUsable({...s.rows[0],quoteAt:s.fetchedAt-120000},s.fetchedAt),false);assert.equal(quoteUsable({...s.rows[0],bid:null},s.fetchedAt),false);assert.equal(quoteUsable({...s.rows[0],ivAt:s.fetchedAt-10000},s.fetchedAt),false);
 assert.throws(()=>fitSABR({...s,rows:s.rows.map(r=>({...r,bid:0}))},{expiry:s.rows[0].expiry}),/forward prices|7 liquid/);assert.throws(()=>fitSABR(s,{expiry:s.rows[0].expiry,beta:1.1}));
});
test('25-delta skew interpolates brackets without extrapolation; gross gamma is positive and signed roots are explicitly hypothetical',()=>{
 const s=optionFixture(),expiry=s.rows[0].expiry,skew=deltaSkew(s,{expiry});assert.ok(skew.call25&&skew.put25);near(skew.riskReversal,skew.call25.iv-skew.put25.iv);assert.match(skew.convention,/no extrapolation/);assert.equal(deltaSkew({...s,rows:s.rows.filter(r=>r.type==='call')},{expiry}).riskReversal,null);
 const gross=gammaExposure(s,{expiry});assert.ok(gross.rows.every(r=>r.call>=0&&r.put>=0));assert.equal(gross.roots.length,0);assert.equal(gammaExposure({...s,rows:s.rows.map(r=>({...r,oi:null}))},{expiry}).qualified,0);const signed=gammaExposure(s,{expiry,convention:'call-positive-put-negative'});assert.match(signed.positioning,/Hypothetical/);assert.ok(signed.rows.every(r=>r.put<=0));
});
test('history validates units, keeps source/hash provenance, imports/exports, compares matched contracts and never prunes at capacity',async()=>{
 const h=new OptionHistory({storage:memory(),maxCount:2}),s=optionFixture(),[a]=await h.save(s),[b]=await h.save({...s,fetchedAt:s.fetchedAt+1000,spot:101});assert.equal((await h.list()).length,2);const first=await h.get(a.id);assert.equal(first.sha256.length,64);const comparison=await h.compare([b.id,a.id]);assert.equal(comparison.changes[0].matched,s.rows.length);near(comparison.changes[0].spotChangePercent,1);
 await assert.rejects(h.save(s),/History is full/);assert.equal((await h.list()).length,2);const imported=new OptionHistory({storage:memory()});await imported.import(JSON.stringify(await h.export([a.id])));assert.match((await imported.list())[0].origin,/not verified/);assert.throws(()=>validateOptionSnapshot({...s,spot:Infinity}));assert.throws(()=>validateOptionSnapshot({...s,rows:[{...s.rows[0],premiumCurrency:'USDC'}]}));await h.remove(b.id);assert.equal((await h.list()).length,1);
});
test('history serializes distinct processes without lost index entries and recovers a dead writer directory',async()=>{
 const dir=await fs.mkdtemp(path.join(os.tmpdir(),'pine-option-lock-'));
 try{await fs.mkdir(path.join(dir,'option-history.lock'));await fs.writeFile(path.join(dir,'option-history.lock','owner-2147483647-dead'),'');const code="import {OptionHistory} from './core/option-history.js';import {optionFixture} from './tests/fixtures/option-chain.js';const h=new OptionHistory();for(let i=0;i<5;i++)await h.save(optionFixture());";
 const run=()=>new Promise((resolve,reject)=>{const p=spawn(process.execPath,['--input-type=module','-e',code],{env:{...process.env,PINE_DESK_DATA_DIR:dir},stdio:['ignore','ignore','pipe']});let error='';p.stderr.on('data',v=>error+=v);p.on('error',reject);p.on('exit',status=>status===0?resolve():reject(Error(error)));});await Promise.all([run(),run()]);const index=JSON.parse(await fs.readFile(path.join(dir,'option-history-index','current.json'),'utf8'));assert.equal(index.length,10);assert.equal(new Set(index.map(r=>r.id)).size,10);
 }finally{await fs.rm(dir,{recursive:true,force:true});}
});
test('recorder captures separately, honors stop generation and exposes capacity failures',async()=>{
 const callbacks=[],history=new OptionHistory({storage:memory(),maxCount:1}),r=new OptionRecorder({history,fetchSnapshot:async()=>optionFixture(),clock:{setTimeout:fn=>{callbacks.push(fn);return 1;},clearTimeout(){}}});r.start();await new Promise(resolve=>setTimeout(resolve,10));assert.equal(r.status().saved,1);await callbacks[0]();assert.equal(r.status().active,false);assert.match(r.status().error,/full/);r.stop();assert.equal((await history.list()).length,1);
});
test('multi-leg linear payoff and Greeks net out, inverse premiums stay in coin, templates are qualified research hypotheses',()=>{
 const s=optionFixture({exchange:'bybit',settlement:'USDC'}),row=s.rows.find(r=>r.strike===100&&r.type==='call'),second=s.rows.find(r=>r.strike===105&&r.type==='call');const risk=portfolioRisk(s,{legs:[{instrument:row.instrument,quantity:1},{instrument:second.instrument,quantity:-1}]});near(risk.entryPremium,row.ask-second.bid);assert.ok(risk.scenarios.every(r=>Number.isFinite(r.expiryPnLSettlement)));assert.match(risk.riskScope,/not global/);assert.ok(strategyCandidates(s,row.expiry).length>=5);
 const inverse=optionFixture(),i=inverse.rows.find(r=>r.strike===100&&r.type==='call'),r=portfolioRisk(inverse,{legs:[{instrument:i.instrument,quantity:1}],spotMin:100,spotMax:200,daysElapsed:365});near(r.scenarios.at(-1).expiryPnLSettlement,.5-i.ask);near(r.cashDelta,-i.ask);assert.equal(r.totalDelta,null);assert.equal(r.greeks.delta,null);
 assert.throws(()=>portfolioRisk(s,{legs:[{instrument:row.instrument,quantity:0}]}));
});
test('quote replay uses both bid/ask sides, exact commission/funding accounting, preserves evidence and rejects gaps/mixed bases',()=>{
 const first=optionFixture({exchange:'bybit',settlement:'USDC'}),id=first.rows.find(r=>r.strike===100&&r.type==='call').instrument,second={...first,fetchedAt:first.fetchedAt+1000,spot:110,rows:first.rows.map(r=>({...r,quoteAt:first.fetchedAt+1000,ivAt:first.fetchedAt+1000,...(r.instrument===id?{bid:15,ask:16}:{})}))};first.rows=first.rows.map(r=>r.instrument===id?{...r,bid:9,ask:10}:r);const records=[{id:'a',sha256:'first',origin:'fixture',snapshot:first},{id:'b',sha256:'second',origin:'fixture',snapshot:second}];
 const result=backtestOptions(records,{legs:[{instrument:id,quantity:2}],initialCapital:1000,feeBps:100,funding:[{time:second.fetchedAt,amount:-1}]});near(result.metrics.netPnLSettlement,8.5);near(result.metrics.feesSettlement,.5);assert.equal(result.fills[0].price,10);assert.equal(result.fills[1].price,15);assert.equal(result.usedQuotes[0].sha256,'first');assert.equal(result.curve[1].funding,-1);
 const broken=structuredClone(records);broken[1].snapshot.rows=[];assert.throws(()=>backtestOptions(broken,{legs:[{instrument:id,quantity:1}]}),/Missing/);const mixed=structuredClone(records);mixed[1].snapshot.exchange='okx';assert.throws(()=>backtestOptions(mixed,{legs:[{instrument:id,quantity:1}]}),/same exchange/);
});
test('inverse replay preserves coin accounting and expiry needs explicit settlement, never a future snapshot index',()=>{
 const first=optionFixture(),id=first.rows.find(r=>r.strike===100&&r.type==='call').instrument;first.rows=first.rows.map(r=>r.instrument===id?{...r,bid:.09,ask:.1}:r);const late={...first,fetchedAt:first.rows[0].expiry+1000,spot:1000,rows:[]};const records=[{id:'a',snapshot:first},{id:'b',snapshot:late}];assert.throws(()=>backtestOptions(records,{legs:[{instrument:id,quantity:1}]}),/official settlement/);const result=backtestOptions(records,{legs:[{instrument:id,quantity:1}],feeBps:0,initialCapital:1,settlement:{price:200,source:'User test fixing'}});near(result.metrics.netPnLSettlement,.4);near(result.metrics.netPnLUSD,80);near(result.curve.at(-1).equityUSD,280);assert.equal(result.curve.at(-1).spot,200);assert.equal(result.curve.at(-1).settlementVerified,false);
});
test('Bybit and OKX normalize IV, quote currencies, contract quantities and missing fields independently',()=>{
 const now=Date.now(),bybit=bybitRows([{symbol:'BTC-2OCT26-100-C-USDT',baseCoin:'BTC',quoteCoin:'USDT',settleCoin:'USDT',status:'Trading',deliveryTime:now+100000,optionsType:'Call'}],[{symbol:'BTC-2OCT26-100-C-USDT',markIv:'.2',markPrice:'10',bid1Price:'',ask1Price:'11',openInterest:'2',underlyingPrice:'100',indexPrice:'100'}],{currency:'BTC',settlement:'USDT',observedAt:now,now});assert.equal(bybit[0].iv,20);assert.equal(bybit[0].bid,null);assert.equal(bybit[0].payoffType,'linear');
 const okx=okxRows([{instId:'BTC-USD-TEST-100-C',instFamily:'BTC-USD',state:'live',settleCcy:'BTC',ctValCcy:'BTC',ctVal:'.01',ctMult:'1',expTime:now+100000,stk:'100',optType:'C'}],[{instId:'BTC-USD-TEST-100-C',bidPx:'.01',askPx:'.02',vol24h:'50',ts:String(now)}],[{instId:'BTC-USD-TEST-100-C',markVol:'.3',fwdPx:'100',ts:String(now),deltaBS:'.5'}],[{instId:'BTC-USD-TEST-100-C',markPx:'.015'}],[{instId:'BTC-USD-TEST-100-C',oi:'100'}],{currency:'BTC',now});near(okx[0].oi,1);near(okx[0].volume,.5);near(okx[0].contractSize,.01);assert.equal(okx[0].iv,30);assert.equal(okx[0].greeks.delta,.5);
});
test('public adapter fixture requests paginate, preserve failures and polling stops cleanly; endpoints reject private/unknown routes',async()=>{
 const now=Date.now(),sent=[],callbacks=[];let fail=false;
 const request=async(e,p,a)=>{sent.push({e,p,a});if(fail)throw Error('HTTP 403');if(p.includes('instruments'))return {result:{list:[{symbol:'BTC-2OCT26-100-C-USDC',baseCoin:'BTC',quoteCoin:'USDC',settleCoin:'USDC',status:'Trading',deliveryTime:now+100000,optionsType:'Call'}]}};return {time:now,result:{list:p.includes('tickers')?[{symbol:'BTC-2OCT26-100-C-USDC',indexPrice:'100',markIv:'.2'}]:[]}};};
 const d=new PublicOptionsExchange('bybit',{request,clock:{setTimeout:fn=>{callbacks.push(fn);return 1;},clearTimeout(){}}});await d.refresh({currency:'BTC',settlement:'USDC'});assert.equal(d.snapshot().rows.length,1);d.start();assert.equal(d.snapshot().status,'polling');d.stop();await callbacks[0]();assert.equal(d.snapshot().active,false);fail=true;await assert.rejects(d.refresh(),/403/);assert.equal(d.snapshot().spot,100);assert.equal(d.snapshot().status,'error');await assert.rejects(exchangeRequest('other','/private'),/Unsupported/);await assert.rejects(exchangeRequest('okx','/api/v5/trade/order'),/Unsupported/);
});

test('archive hash checks detect edits and failed index writes roll back new documents',async()=>{
 const storage=memory(),h=new OptionHistory({storage}),[record]=await h.save(optionFixture());const edited=await storage.read('option-history',record.id);edited.snapshot.spot=101;await storage.write('option-history',edited,record.id);await assert.rejects(h.get(record.id),/hash mismatch/);
 const clean=memory(),write=clean.write,removed=[];clean.write=async(k,v,id)=>{if(k==='option-history-index')throw Error('disk full');return write(k,v,id);};const remove=clean.remove;clean.remove=async(k,id)=>{removed.push(id);return remove(k,id);};await assert.rejects(new OptionHistory({storage:clean}).save(optionFixture()),/disk full/);assert.equal(removed.length,1);assert.equal(await clean.read('option-history',removed[0]),null);
});
