import {test,expect} from '@playwright/test';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
let dir,dispatch;
test.beforeAll(async()=>{dir=await fs.mkdtemp(path.join(os.tmpdir(),'pine-desk-ui-'));process.env.PINE_DESK_DATA_DIR=dir;({dispatch}=await import('../../core/service.js'));});
test.afterAll(async()=>{await fs.rm(dir,{recursive:true,force:true});});
test('chart, Pine worker, actual backtest backend, analysis tabs, and order flow',async({page})=>{
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.exposeFunction('backendCall',(action,args)=>dispatch(action,args));
  await page.addInitScript(()=>{window.desk={call:(a,b)=>window.backendCall(a,b)};});
  await page.goto('/');
  await expect(page.locator('#source')).toBeVisible();
  await expect(page.locator('#chart canvas').first()).toBeVisible();
  await page.locator('#run-chart').click();
  await expect(page.locator('#toast')).toContainText('Script rendered',{timeout:30000});
  await page.locator('#run-backtest').click();
  await expect(page.locator('#title')).toHaveText('Strategy research',{timeout:30000});
  await expect(page.locator('#equity-plot')).toBeVisible();
  await page.locator('[data-tab="log"]').click();
  await expect(page.locator('tbody tr')).toHaveCount(5);
  await page.locator('[data-tab="analysis"]').click();
  await expect(page.locator('#trade-plot')).toBeVisible();
  await page.locator('[data-tab="simulation"]').click();
  await page.locator('#simulate').click();
  await expect(page.locator('#simulation-metrics')).toContainText('Median');
  await dispatch('importTrades',{symbol:'FIXTURE',csv:'time,price,size,side\n1767225600,65000,2,buy\n1767225601,65010,1,sell\n1767229200,65020,3,buy'});
  await page.locator('[data-page="orderflow"]').click();await page.locator('#refresh-flow').click();
  await expect(page.locator('#cvd-plot')).toBeVisible();
  await page.locator('[data-page="mcp"]').click();await expect(page.getByText('MCP CLIENT CONFIGURATION')).toBeVisible();
  await page.locator('[data-page="workspace"]').click();
  await expect(page.locator('#chart')).toHaveAttribute('data-ready','true');
  await page.screenshot({path:'test-results/workspace.png',fullPage:true});
  expect(errors).toEqual([]);
});
test('library browse, search, import and saved Pine source',async({page})=>{
  const source='//@version=6\nindicator("Library fixture", overlay=true)\nplot(ta.ema(close, 20), "EMA")';
  await page.exposeFunction('backendCall',(action,args)=>{
    if(action==='libraryList')return {total:1,indicators:[{slug:'fixture',name:'Library fixture',family:'trend',description:'A local test fixture.'}]};
    if(action==='librarySearch')return {results:[{slug:'fixture',name:'Library fixture',family:'trend',description:'A local test fixture.'}]};
    if(action==='librarySource')return {available:true,slug:'fixture',name:'Library fixture',source};
    return dispatch(action,args);
  });
  await page.addInitScript(()=>{window.desk={call:(a,b)=>window.backendCall(a,b)};});
  await page.goto('/');await expect(page.locator('#status')).toHaveText('Local workspace');
  await page.locator('[data-page="library"]').click();
  await page.locator('#browse-empty').click();
  await expect(page.locator('.library-card h3')).toHaveText('Library fixture');
  await page.locator('#library-query').fill('EMA');await page.locator('#search-library').click();
  await expect(page.locator('[data-import-source]')).toBeVisible();
  await page.locator('[data-import-source]').click();
  await expect(page.locator('#source')).toHaveValue(source);
  await page.locator('#run-chart').click();await expect(page.locator('#toast')).toContainText('Script rendered');
  const workspace=await dispatch('workspace');assertSource(workspace,source);
});
function assertSource(workspace,source){expect(workspace.scripts.some(s=>s.source===source&&s.provenance?.slug==='fixture')).toBeTruthy();}
test('Edge Stats evidence and Whale Options audit panels preserve upstream caveats',async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const config={mode:'local',endpoint:'http://127.0.0.1:3344/mcp'};
 const report={n:2,successes:1,estimate:null,ci95:null,query:{dsl:'gapFill',outcome:'gapFill',symbol:'TEST',sessionKey:'rth'},guards:{lowSample:true,refused:true},disclaimer:'Historical conditional frequencies. Not predictions.',sessions:[],perYear:[]};
 await page.exposeFunction('backendCall',async(action,args)=>{
  if(action==='edgeConfigure')return config;
  if(action==='edgeOverview')return {config,coverage:{symbols:[{symbol:'TEST',tf:'1m',lastBar:'2024-12-30T20:59:00Z'}],engineVersion:'0.1.0'},catalog:{presets:[{id:'gap-fill',title:'Gap Fill',summary:'Test definition'}]},retrievedAt:Date.now()};
  if(action==='edgeReport')return {config,result:report,retrievedAt:Date.now()};
  if(action==='whaleConfigure')return args;
  if(action==='whaleStatus')return {result:{ticks:100,events:1,cold_start:true,live_engine:false,baseline_sessions:0,chains_available:[{underlying:'NVDA'}]}};
  if(action==='whaleRecent')return {result:{events:[{id:'test',ts:Date.now(),underlying:'NVDA',contract:'FIXTURE',kind:'sweep',side:'unknown',premium:50000,score:60,cold_start:true}]}};
  if(action==='whaleEvent')return {result:{id:'test',cold_start:true,legs_detail:[{nbbo_at_print:null}],score_breakdown:{missing:['volumeVsBaseline']}}};
  if(action==='whaleGex')return {result:{snapshot_age_ms:60000,gex:{convention:'dealer-long-calls-short-puts',conventionNote:'Dealer positioning is an assumption.',totalGex:1,perStrike:[],skippedContracts:0}}};
  return dispatch(action,args);
 });
 await page.addInitScript(()=>{window.desk={call:(a,b)=>window.backendCall(a,b)};});
 await page.goto('/');await expect(page.locator('#status')).toHaveText('Local workspace');
 await page.locator('[data-page="edge"]').click();await page.locator('#edge-mode').selectOption('local');await page.locator('#edge-connect').click();
 await expect(page.locator('#edge-symbol')).toHaveValue('TEST');
 await page.locator('#edge-run-report').click();await expect(page.locator('.edge-warning')).toContainText('ESTIMATE WITHHELD');
 await expect(page.locator('.edge-metrics')).toContainText('Withheld');await expect(page.locator('.edge-metrics')).toContainText('2');
 await page.locator('[data-page="whale"]').click();await page.locator('#whale-source').selectOption('synthetic');await page.locator('#whale-connect').click();
 await expect(page.locator('#whale-panel')).toContainText('COLD START');await page.locator('#whale-recent').click();
 await expect(page.locator('#whale-panel tbody')).toContainText('unknown');await page.locator('[data-whale-event]').click();
 await expect(page.locator('#whale-panel')).toContainText('nbbo_at_print');await page.locator('[data-whale-analysis="gex"]').click();
 await expect(page.locator('#whale-panel')).toContainText('Dealer positioning is an assumption.');
 expect(errors).toEqual([]);
});
